spring.application.name=parking

spring.data.mongodb.uri=mongodb+srv://Jgomez:52134Jg2005@cluster0.br6d4qz.mongodb.net/parking?appName=Cluster0
spring.data.mongodb.database=parking

server.port=8444
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=parking123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=parking
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=false

# === SESIÓN Y COOKIES ===
server.servlet.session.timeout=15m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true

# === CONFIGURACIÓN DE CORREO ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=josephgomeztatis@gmail.com
spring.mail.password=epkk gupe xsea gkhy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
